### ISSUE TITLE
Roadmap, or target

### ISSUE THREAD

**Issue by kination** [clio-lang/rio#1]
Hello~can I ask you the purpose of this project?
I know it is related with clio, and it is something experimental. 

Just want to know what you want to get through this, because it seems it is in active state... 🙏

**Comment by garritfra** [comment]
It was just an experiment for a new compiler design in rust. We discussed switching to a more appropriate language for compilers, but we first want to develop a more stable version of the current compiler, before we tackle a full redesign.
